/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.doctor;

import controller.DoctorController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DoctorModel;

/**
 *
 * @author Fayami
 */
public class IntDoctor extends javax.swing.JInternalFrame {
    DoctorController doctorControl;
    /**
     * Creates new form IntDoctor
     */
    public IntDoctor() {
        initComponents();
        doctorControl = new DoctorController(this);
        getAllDoctor();
    }

    public void getAllDoctor(){
        try {
            ArrayList<DoctorModel> list = doctorControl.getAllDoctor();
            DefaultTableModel model = (DefaultTableModel)doctorTable.getModel();
            model.setRowCount(0);
            Object[] row = new Object[5];
            for(int i = 0; i < list.size(); i++){
                row[0] = list.get(i).getId();
                row[1] = list.get(i).getFullName();
                row[2] = list.get(i).getNumberPhone();
                row[3] = list.get(i).getAddress();
                row[4] = list.get(i).getEmail();
                model.addRow(row);
            }
            textBoxDisabled();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void textBoxDisabled(){
        
        txtID.setText("");
        txtDoctorName.setText("");
        txtAddress.setText("");
        txtNumberPhone.setText("");
        txtEmail.setText("");
        
        txtID.setEnabled(false);
        txtDoctorName.setEnabled(false);
        txtAddress.setEnabled(false);
        txtNumberPhone.setEnabled(false);
        txtEmail.setEnabled(false);
        
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
    }
    
    public void textBoxEnabled(){
        txtID.setEnabled(true);
        txtDoctorName.setEnabled(true);
        txtAddress.setEnabled(true);
        txtNumberPhone.setEnabled(true);
        txtEmail.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnDelete.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientForm = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNumberPhone = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnAddPatient = new javax.swing.JButton();

        PatientForm.setBackground(new java.awt.Color(0, 153, 153));
        PatientForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(15, 185, 177));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctor Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        PatientForm.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 770, 60));

        doctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Doctor", "Name Doctor", "Number Phone", "Address", "Email"
            }
        ));
        doctorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctorTable);

        PatientForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 700, 150));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("ID Doctor");
        PatientForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Name Doctor");
        PatientForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");
        PatientForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("Email");
        PatientForm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        txtID.setBackground(new java.awt.Color(204, 204, 255));
        txtID.setBorder(null);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        PatientForm.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 110, 30));

        txtDoctorName.setBackground(new java.awt.Color(204, 204, 255));
        txtDoctorName.setBorder(null);
        PatientForm.add(txtDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 190, 30));

        txtAddress.setBackground(new java.awt.Color(204, 204, 255));
        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setBorder(null);
        jScrollPane2.setViewportView(txtAddress);

        PatientForm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 190, 80));

        txtEmail.setBackground(new java.awt.Color(204, 204, 255));
        txtEmail.setBorder(null);
        PatientForm.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 190, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setText("Number Phone");
        PatientForm.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txtNumberPhone.setBackground(new java.awt.Color(204, 204, 255));
        txtNumberPhone.setBorder(null);
        PatientForm.add(txtNumberPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 190, 30));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        PatientForm.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 80, 30));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        PatientForm.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 80, 30));

        btnAddPatient.setText("Add Doctor Data");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });
        PatientForm.add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PatientForm, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientForm, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        boolean hasil = doctorControl.deleteDoctor(Integer.parseInt(txtID.getText()));
        if(hasil){
            getAllDoctor();
            JOptionPane.showMessageDialog(null,"Data Berhasil dihapus");
        }else{
            JOptionPane.showMessageDialog(null,"Data Gagal dihapus");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        boolean hasil = doctorControl.updateDoctor(
                Integer.parseInt(txtID.getText()),
                txtDoctorName.getText(),
                txtNumberPhone.getText(), 
                txtAddress.getText(), 
                txtEmail.getText()
        );
        if(hasil){
            getAllDoctor();
            JOptionPane.showMessageDialog(null,"Data Berhasil diubah");
        }else{
            JOptionPane.showMessageDialog(null,"Data gagal diubah");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        DoctorRegister formRegister = new DoctorRegister(this);
        formRegister.setResizable(false);
        formRegister.setDefaultCloseOperation(DoctorRegister.DO_NOTHING_ON_CLOSE);
        formRegister.setVisible(true);
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void doctorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorTableMouseClicked
        // TODO add your handling code here:
         int row = doctorTable.getSelectedRow();
         String table_click = doctorTable.getModel().getValueAt(row, 0).toString();
         System.out.println(table_click);
        try {
            DoctorModel doctor = doctorControl.getOneDoctor(table_click);
            txtID.setText(String.valueOf(doctor.getId()));
            txtDoctorName.setText(doctor.getFullName());
            txtAddress.setText(doctor.getAddress());
            txtNumberPhone.setText(doctor.getNumberPhone());
            txtEmail.setText(doctor.getEmail());
            textBoxEnabled();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
         
    }//GEN-LAST:event_doctorTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PatientForm;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JTable doctorTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNumberPhone;
    // End of variables declaration//GEN-END:variables
}
