/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.patient;

/**
 *
 * @author codexhaq
 */
public class IntPatient extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public IntPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientForm = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNamaPasien = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNoIdentitas1 = new javax.swing.JTextField();
        rdbPerempuan = new javax.swing.JRadioButton();
        rdbLaki = new javax.swing.JRadioButton();
        btnEdit = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnMedicalRecord = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        btnAddPatient = new javax.swing.JButton();

        PatientForm.setBackground(new java.awt.Color(0, 153, 153));
        PatientForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(15, 185, 177));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        PatientForm.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Patient", "Nama Pasien", "Alamat", "No. Identitas", "Tanggal Lahir", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PatientForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 700, 150));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("ID Patient");
        PatientForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Nama Pasien");
        PatientForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");
        PatientForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        PatientForm.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("Email");
        PatientForm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setText("Tanggal Lahir");
        PatientForm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 20));

        txtID.setBackground(new java.awt.Color(204, 204, 255));
        txtID.setBorder(null);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        PatientForm.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 110, 30));

        txtNamaPasien.setBackground(new java.awt.Color(204, 204, 255));
        txtNamaPasien.setBorder(null);
        PatientForm.add(txtNamaPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, 30));

        txtAlamat.setBackground(new java.awt.Color(204, 204, 255));
        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.setBorder(null);
        jScrollPane2.setViewportView(txtAlamat);

        PatientForm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 190, 80));

        txtEmail.setBackground(new java.awt.Color(204, 204, 255));
        txtEmail.setBorder(null);
        PatientForm.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 190, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setText("No. Identitas");
        PatientForm.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        txtNoIdentitas1.setBackground(new java.awt.Color(204, 204, 255));
        txtNoIdentitas1.setBorder(null);
        PatientForm.add(txtNoIdentitas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 190, 30));

        rdbPerempuan.setBackground(new java.awt.Color(204, 204, 255));
        rdbPerempuan.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdbPerempuan.setText("Perempuan");
        rdbPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPerempuanActionPerformed(evt);
            }
        });
        PatientForm.add(rdbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, 30));

        rdbLaki.setBackground(new java.awt.Color(204, 204, 255));
        rdbLaki.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdbLaki.setText("Laki - Laki");
        rdbLaki.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PatientForm.add(rdbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, 30));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        PatientForm.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 80, 30));
        PatientForm.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 190, -1));

        btnMedicalRecord.setText("Medical Record");
        btnMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalRecordActionPerformed(evt);
            }
        });
        PatientForm.add(btnMedicalRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 170, 30));

        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        PatientForm.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 80, 30));

        btnAddPatient.setText("Add Patient Data");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });
        PatientForm.add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PatientForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientForm, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void rdbPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbPerempuanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicalRecordActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        PatientRegister formRegister = new PatientRegister();
        formRegister.setResizable(false);
        formRegister.setDefaultCloseOperation(PatientRegister.DO_NOTHING_ON_CLOSE);
        formRegister.setVisible(true);
    }//GEN-LAST:event_btnAddPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PatientForm;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMedicalRecord;
    private javax.swing.JButton btnSave1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdbLaki;
    private javax.swing.JRadioButton rdbPerempuan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNamaPasien;
    private javax.swing.JTextField txtNoIdentitas1;
    // End of variables declaration//GEN-END:variables
}
